// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thponngagljdnzijrhmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRocG9ubmdhZ2xqZG56aWpyaG1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MDYzODYsImV4cCI6MjA2NjE4MjM4Nn0.b1hhOaIXV3-JxXyFZNuqzw43osLZjqjMiq3QQPKlmic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);